feat: #29 리스트 내 맛집 검색 기능 구현
taste-house/mat_zip pull request #149
Opened 2024-09-27 15:25 UTC by WhooGeek

🌟개요
리스트 내 맛집 검색 기능 구현

🌐연결된 Issues
#29 

📋작업사항
리스트 내에 맛집을 조회하는 기능을 구현했습니다
음식점 조회와의 차이점은 WHERE 절로 2개의 조건을 추가한 것입니다.
1. listSeq 입력과 일치하는지
2. restaurantTitle과 일치하는지(LIKE문으로 한글자라도 포함되면 검색에 걸리도록 설정하였습니다)

✏️작성한 이슈 외 작업사항
---

✅체크리스트
---
- [ ] PR 규칙을 준수하였는가?
- [ ] 이슈번호를 작성하였는가?
- [ ] 추가/수정 사항을 설명하였는가?

2024-09-27 15:46 UTC, wildcat222 approved these changes

2024-09-27 16:09 UTC, catnine11 requested changes

2024-09-27 16:09 UTC, catnine11 commented on matzipback/src/main/resources/mappers/listMappers/MatzipQueryMapper.xml
> +               (r.restaurant_title LIKE CONCAT('%' #{matzipTitle} '%') OR #{matzipTitle} IS NULL)
이거 혹시 잘 작동하나요? CONCAT('%', #{matzipTitle}, '%') < 이렇게 사이에 , 써줘야 하지않나요?

2024-09-27 16:19 UTC, catnine11 commented on matzipback/src/main/resources/mappers/listMappers/MatzipQueryMapper.xml
> +               (r.restaurant_title LIKE CONCAT('%' #{matzipTitle} '%') OR #{matzipTitle} IS NULL)
이거 혹시 잘 작동하나요? CONCAT('%', #{matzipTitle}, '%') < 이렇게 사이에 , 써줘야 하지않나요?

2024-09-27 18:00 UTC, leebackcoding commented on matzipback/src/main/resources/mappers/listMappers/MatzipQueryMapper.xml
> +               (r.restaurant_title LIKE CONCAT('%' #{matzipTitle} '%') OR #{matzipTitle} IS NULL)
이것만 확인해주시면 될거같아용
미리 승인 해놓을게요

2024-09-27 18:01 UTC, leebackcoding approved these changes

2024-09-28 04:08 UTC, WhooGeek commented on matzipback/src/main/resources/mappers/listMappers/MatzipQueryMapper.xml
> +               (r.restaurant_title LIKE CONCAT('%' #{matzipTitle} '%') OR #{matzipTitle} IS NULL)
넵 테스트 해보고 올렸씁니다!

2024-09-28 04:08 UTC, merged